name: Vocab Word of the Hour

on:
  schedule:
    - cron: '0,30 4-17 * * *'  # Runs at :00 and :30 UTC = 10:00 AM - 11:30 PM IST
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-vocab-word:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests pytz

      - name: Run script
        run: python My_Vocab.py
