name: Vocab Word of the Hour

on:
  schedule:
    - cron: '0 4-17 * * *'  # 4:30 AM to 5:30 PM UTC = 10:00 AM to 11:00 PM IST
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-vocab-word:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests pytz

      - name: Run script
        run: python My_Vocab.py
